### ISSUE TITLE
Implement splats

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/cigale#2]
Something like:

``` yaml
- :macro:
    - a: '{key}'
    - b: '{key}'

- ..triggers:
    key: value

- c: hi!
```

would expand to:

``` yaml
- a: value
- b: value
- c: hi!
```

The syntax can be thought of as file paths: `.` means "expand here", `..` means "expand to parent node".

Implementation will need to change from `map` to imperative adding to a temporary array, to handle sub-calls to expand returning `Splat`.
