### ISSUE TITLE
Support default values in macros

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/cigale#3]
``` yaml
:deploy-somewhere:
  :defaults:
    public: false
  somewhere:
    bucket: wherever
    share-publicly: '{public}'
```

For array macros:

``` yaml
:deploy-somewhere:
  - :defaults:
      public: false
  - somewhere:
      bucket: wherever
      share-publicly: '{public}'
```

Bit hacky but eh, it'll do
